//! Per-engine asset emission: turn an exported pack into files a specific game
//! engine wires automatically — Godot `.import` sidecars (loop mode preserved),
//! Unity `.meta` sidecars (stable deterministic GUIDs, so references survive
//! re-export on any machine), and a generated Rust module for Bevy.

use std::path::Path;

use schemars::JsonSchema;
use serde::Deserialize;

use crate::bank::ManifestEntry;

/// Engine flavour to emit alongside an exported pack.
#[derive(Debug, Clone, Copy, Deserialize, JsonSchema, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum EngineTarget {
    /// Godot 4: a `.import` sidecar per WAV/OGG with the loop mode set, so a
    /// looped bed imports looping without touching the import dock.
    Godot,
    /// Unity: a `.meta` sidecar per file with a deterministic GUID derived from
    /// the sound id — references stay stable across machines and re-exports.
    Unity,
    /// Bevy: a generated `sonarium_sounds.rs` with an enum of every sound, its
    /// asset path, and loop flag — compile-time-checked asset keys.
    Bevy,
}

/// Emit engine files into `dest` for `entries`. Returns the relative paths of
/// every file written.
pub fn emit(
    engine: EngineTarget,
    dest: &Path,
    entries: &[ManifestEntry],
) -> anyhow::Result<Vec<String>> {
    match engine {
        EngineTarget::Godot => godot(dest, entries),
        EngineTarget::Unity => unity(dest, entries),
        EngineTarget::Bevy => bevy(dest, entries),
    }
}

/// Godot 4 `.import` sidecars. Godot fills in `uid`/cache paths on first scan;
/// the part worth shipping is the importer choice and the loop parameters.
fn godot(dest: &Path, entries: &[ManifestEntry]) -> anyhow::Result<Vec<String>> {
    let mut written = Vec::new();
    for e in entries {
        let body = if e.file.ends_with(".wav") {
            format!(
                "[remap]\n\nimporter=\"wav\"\ntype=\"AudioStreamWAV\"\n\n[params]\n\nforce/8_bit=false\nforce/mono=false\nedit/trim=false\nedit/normalize=false\nedit/loop_mode={}\nedit/loop_begin=0\nedit/loop_end=-1\ncompress/mode=0\n",
                if e.looped { 1 } else { 0 }
            )
        } else if e.file.ends_with(".ogg") {
            format!(
                "[remap]\n\nimporter=\"oggvorbisstr\"\ntype=\"AudioStreamOggVorbis\"\n\n[params]\n\nloop={}\nloop_offset=0\nbpm=0\nbeat_count=0\nbar_beats=4\n",
                e.looped
            )
        } else {
            // Godot has no native FLAC importer — skip.
            continue;
        };
        let rel = format!("{}.import", e.file);
        std::fs::write(dest.join(&rel), body)?;
        written.push(rel);
    }
    Ok(written)
}

/// Unity `.meta` sidecars with a deterministic GUID per sound id. Unity
/// upgrades the AudioImporter block to its own serialized version on import;
/// the GUID is the part that must stay stable.
fn unity(dest: &Path, entries: &[ManifestEntry]) -> anyhow::Result<Vec<String>> {
    let mut written = Vec::new();
    for e in entries {
        let body = format!(
            "fileFormatVersion: 2\nguid: {}\nAudioImporter:\n  externalObjects: {{}}\n  serializedVersion: 6\n  defaultSettings:\n    loadType: 0\n    sampleRateSetting: 0\n    sampleRateOverride: {}\n    compressionFormat: 1\n    quality: 0.5\n    conversionMode: 0\n  forceToMono: 0\n  normalize: 1\n  preloadAudioData: 1\n  loadInBackground: 0\n  ambisonic: 0\n  3D: 1\n  userData: \n  assetBundleName: \n  assetBundleVariant: \n",
            guid_hex32(&e.id),
            e.sample_rate
        );
        let rel = format!("{}.meta", e.file);
        std::fs::write(dest.join(&rel), body)?;
        written.push(rel);
    }
    Ok(written)
}

/// A generated Rust module for Bevy: enum + asset path + loop flag, so game
/// code references sounds with compile-time-checked keys.
fn bevy(dest: &Path, entries: &[ManifestEntry]) -> anyhow::Result<Vec<String>> {
    let mut out = String::from(
        "//! Generated by sonarium `export_bank` — do not edit.\n//! Asset keys for every exported sound; paths are relative to the export dir\n//! (point your `AssetServer` base or prefix accordingly).\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum Sound {\n",
    );
    for e in entries {
        out.push_str(&format!("    {},\n", pascal(&e.id)));
    }
    out.push_str("}\n\nimpl Sound {\n    pub const ALL: &[Sound] = &[\n");
    for e in entries {
        out.push_str(&format!("        Sound::{},\n", pascal(&e.id)));
    }
    out.push_str("    ];\n\n    /// Asset path of this sound's file.\n    pub fn path(self) -> &'static str {\n        match self {\n");
    for e in entries {
        out.push_str(&format!(
            "            Sound::{} => \"{}\",\n",
            pascal(&e.id),
            e.file
        ));
    }
    out.push_str("        }\n    }\n\n    /// True when the file is a seamless loop.\n    pub fn looped(self) -> bool {\n        match self {\n");
    for e in entries {
        out.push_str(&format!(
            "            Sound::{} => {},\n",
            pascal(&e.id),
            e.looped
        ));
    }
    out.push_str("        }\n    }\n}\n");
    let rel = "sonarium_sounds.rs".to_string();
    std::fs::write(dest.join(&rel), out)?;
    Ok(vec![rel])
}

/// `laser_zap_2` → `LaserZap2`.
fn pascal(slug: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in slug.chars() {
        if c == '_' || c == '-' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, 'S');
    }
    out
}

/// Stable 32-hex-digit id derived from `s` (FNV + SplitMix mix — uniqueness and
/// stability, not cryptography). Used as the Unity GUID.
fn guid_hex32(s: &str) -> String {
    let mut h1: u64 = 0xcbf2_9ce4_8422_2325;
    let mut h2: u64 = 0x9e37_79b9_7f4a_7c15;
    for &b in s.as_bytes() {
        h1 = (h1 ^ b as u64).wrapping_mul(0x0000_0100_0000_01b3);
        h2 = h2
            .wrapping_add(b as u64)
            .wrapping_mul(0xbf58_476d_1ce4_e5b9);
        h2 ^= h2 >> 27;
    }
    format!("{h1:016x}{h2:016x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(id: &str, file: &str, looped: bool) -> ManifestEntry {
        ManifestEntry {
            id: id.into(),
            name: id.into(),
            file: file.into(),
            category: None,
            rr_group: None,
            looped,
            duration_ms: 100,
            sample_rate: 44_100,
            channels: 1,
            lufs: -16.0,
            peak_dbfs: -1.0,
            true_peak_dbfs: -0.9,
        }
    }

    fn tmp() -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "sonarium_engines_{}",
            std::process::id() // unique per test run
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn unity_guids_are_deterministic_and_distinct() {
        assert_eq!(guid_hex32("laser"), guid_hex32("laser"));
        assert_ne!(guid_hex32("laser"), guid_hex32("coin"));
        assert_eq!(guid_hex32("laser").len(), 32);
    }

    #[test]
    fn pascal_handles_separators_and_digit_starts() {
        assert_eq!(pascal("laser_zap_2"), "LaserZap2");
        assert_eq!(pascal("ui-click"), "UiClick");
        assert_eq!(pascal("8bit_hit"), "S8bitHit"); // valid Rust identifier
    }

    #[test]
    fn godot_emits_import_sidecars_with_loop_mode() {
        let dir = tmp();
        let written = emit(
            EngineTarget::Godot,
            &dir,
            &[
                entry("amb", "amb.wav", true),
                entry("hit", "hit.flac", false),
            ],
        )
        .unwrap();
        assert_eq!(written, vec!["amb.wav.import"]); // FLAC skipped
        let body = std::fs::read_to_string(dir.join("amb.wav.import")).unwrap();
        assert!(body.contains("edit/loop_mode=1"));
    }

    #[test]
    fn bevy_module_lists_every_sound() {
        let dir = tmp();
        let written = emit(
            EngineTarget::Bevy,
            &dir,
            &[
                entry("laser", "laser.wav", false),
                entry("amb", "amb.ogg", true),
            ],
        )
        .unwrap();
        assert_eq!(written, vec!["sonarium_sounds.rs"]);
        let body = std::fs::read_to_string(dir.join("sonarium_sounds.rs")).unwrap();
        assert!(body.contains("Sound::Laser => \"laser.wav\""));
        assert!(body.contains("Sound::Amb => true"));
    }
}
